a = input("Enter First String: ")
b = input("Enter Second String: ")

print("1. Concatenation:", a + b)
print("")
print("2. Reversal:- String 1:", a[::-1], ", String 2:", b[::-1])
print("")
print("3. Slicing Till 3rd Character:- String 1:", a[0:3], ", String 2:", b[0:3])
print("")
print("4. Length:- String 1 =", len(a), ", String 2 =", len(b))
print("")
print("5. Comparison:-", a == b)
print("")
print("6. 3 times Repetition:- String 1:", a * 3)
print("")
print("7. Count of 'o' in String 1:- String 1:", a.count('o'))
print("")
print("8. Replacing 'a' with 'b' in String 2:-  String 2:", b.replace('a', 'b'))
print("")
print("10. Converting both strings to uppercase:- String 1:", a.upper(), ", String 2:", b.upper())
print("")
print("11. Converting both strings to lowercase:- String 1:", a.lower(), ", String 2:", b.lower())
print("")
print("12. Swapping case of both strings:- String 1:", a.swapcase(), ", String 2:", b.swapcase())
print("")
print(f"13. split():- {a.split()}")
print("")
print(f"14. strip():- {b.strip()}")



